FROM ubuntu:24.04
RUN apt-get update \
&& apt-get dist-upgrade -y \
&& apt-get autoremove -y \
&& apt-get autoclean -y \
&& apt-get install -y \
sudo \
nano \
wget \
curl \
git
RUN useradd -G sudo -m -d /home/cliffordvaliente -s /bin/bash -p "$(openssl cliffordvaliente -1 PASSWRD)" cliffordvaliente
USER cliffordvaliente
WORKDIR /home/cliffordvaliente
RUN mkdir hacking \
&& cd hacking \
&& curl -SL https://raw.githubusercontent.com/uia-worker/is105misc/master/sem01v24/pawned.sh > pawned.sh \
&& chmod 764 pawned.sh \
&& cd ..
RUN git config --global user.email "cliffordvaliente"\
&& git config --global user.name "cliffordvaliente" \
&& git config --global url."https://PAT:@github.com/".insteadOf"https://github.com" \
&& mkdir -p github.com/cliffordvaliente
USER root
RUN curl -SL https://go.dev/dl/go1.21.6.linux-arm64.tar.gz \
| tar xvz -C /usr/local
USER cliffordvaliente
SHELL ["/bin/bash", "-c"]
RUN mkdir -p $HOME/go/{src,bin}
ENV GOPATH="/home/cliffordvaliente/go"
ENV PATH="${PATH}:${GOPATH}/bin:/usr/local/go/bin"